#!/bin/bash
# 🚀 MONDAY LAUNCH - ONE-LINE COMMANDS
# MAE: 5.363 (CHAMPIONSHIP LEVEL!)

echo "════════════════════════════════════════════════════════════════"
echo "🏆 ONTOLOGIC XYZ - CHAMPIONSHIP SYSTEM LAUNCH"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "MAE: 5.363 (vs research benchmark 5-7)"
echo "Status: ✅ CHAMPIONSHIP LEVEL"
echo "Launch: Monday 4:00 PM PST"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "⚡ ONE-LINE COMMANDS - COPY/PASTE TO LAUNCH"
echo "════════════════════════════════════════════════════════════════"
echo ""

echo "1️⃣  CHECK SYSTEM STATUS:"
echo "   cd '/Users/test/Desktop/Tuscan Money/Ontologic XYZ/ML Research/Action' && python3 -c \"import pickle; m=pickle.load(open('MEGA_ENSEMBLE_CHAMPION.pkl','rb')); print(f'MAE: {m[\\\"champion_mae\\\"]:.3f} | Strategy: {m[\\\"champion_name\\\"]}')\" "
echo ""

echo "2️⃣  TEST PREDICTION (dry run):"
echo "   cd '/Users/test/Desktop/Tuscan Money/Ontologic XYZ/ML Research/Action' && python3 -c \"import pickle,numpy as np; m=pickle.load(open('MEGA_ENSEMBLE_CHAMPION.pkl','rb')); test_pattern=[0,2,-1,3,2,-2,0,5,3,1,-1,2,4,3,1,0,-2,1]+[0]*10; pred=m['base_models']['xgboost'].predict([test_pattern]); print(f'Prediction: {pred[0]:.1f} points')\""
echo ""

echo "3️⃣  LAUNCH GAME ENGINE (Monday 3:30 PM - before games):"
echo "   cd '/Users/test/Desktop/Tuscan Money/Ontologic XYZ/ML Research/Action' && python3 game_engine.py &"
echo ""

echo "4️⃣  MONITOR LIVE (during games):"
echo "   cd '/Users/test/Desktop/Tuscan Money/Ontologic XYZ/ML Research/Action' && tail -f game_engine.log"
echo ""

echo "5️⃣  CHECK TRADES (after session):"
echo "   cd '/Users/test/Desktop/Tuscan Money/Ontologic XYZ/ML Research/Action' && python3 -c \"import pandas as pd; df=pd.read_csv('trades.csv'); print(df.tail(10))\""
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "🎯 SYSTEM SPECS"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "  • MAE: 5.363 (Championship level)"
echo "  • Confidence intervals: 90% coverage"
echo "  • Ensemble: 10 strategies tested, best selected"
echo "  • Base models: 5 (XGBoost, ExtraTrees, LightGBM, RF, HistGB)"
echo "  • Risk layers: 5 (Kelly → Delta → Portfolio → Decision → Final)"
echo "  • Max bet: \$750 (15% cap)"
echo "  • Better Buzz WiFi: ✅ Optimized"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "📋 PRE-LAUNCH CHECKLIST"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Sunday 3:00 PM:"
echo "  [ ] Run command #1 (check system)"
echo "  [ ] Run command #2 (test prediction)"
echo "  [ ] Review risk config"
echo "  [ ] Mental preparation"
echo ""
echo "Monday 3:30 PM:"
echo "  [ ] Run command #3 (launch engine)"
echo "  [ ] Open dashboard"
echo "  [ ] Monitor command #4"
echo ""
echo "Monday 4:00 PM:"
echo "  [ ] First games start"
echo "  [ ] Watch predictions"
echo "  [ ] Track bets"
echo ""
echo "════════════════════════════════════════════════════════════════"

