"""
Bet Tracking Data Models
For recording user bets and tracking performance
"""

from typing import TypedDict, Optional
from enum import Enum


class BetType(str, Enum):
    """Type of bet placed"""
    SPREAD = "spread"
    TOTAL = "total"
    MONEYLINE = "moneyline"


class BetOutcomeStatus(str, Enum):
    """Outcome of a bet"""
    PENDING = "pending"
    WON = "won"
    LOST = "lost"
    PUSH = "push"


class BetEntry(TypedDict):
    """
    Record of a bet placed by the user
    """
    # Bet identification
    bet_id: Optional[int]  # Auto-generated by database
    game_id: str
    
    # Game context
    home_team: str
    away_team: str
    quarter_placed: int
    time_placed: str
    
    # Bet details
    bet_type: str  # spread, total, moneyline
    bet_side: str  # home, away, over, under
    bet_amount: float
    odds_american: int  # e.g., -110
    
    # Market odds (from BetOnline)
    market_spread: Optional[float]
    market_total: Optional[float]
    market_home_ml: Optional[int]
    market_away_ml: Optional[int]
    
    # ML prediction at time of bet
    ml_predicted_spread: Optional[float]
    ml_win_probability: Optional[float]
    ml_confidence: Optional[float]
    edge: Optional[float]  # Calculated edge
    
    # Outcome (filled after game ends)
    outcome: Optional[str]  # won, lost, push, pending
    profit_loss: Optional[float]
    
    # Metadata
    placed_at: str
    resolved_at: Optional[str]


class BetOutcome(TypedDict):
    """Final outcome of a bet after game completes"""
    bet_id: int
    game_id: str
    
    # Actual results
    final_home_score: int
    final_away_score: int
    actual_spread: float
    actual_total: float
    
    # Bet result
    outcome: str  # won, lost, push
    profit_loss: float
    roi: float
    
    # ML accuracy
    ml_prediction_error: Optional[float]
    ml_was_correct: bool
    
    # Timestamp
    resolved_at: str


def calculate_bet_outcome(
    bet: BetEntry,
    final_home_score: int,
    final_away_score: int
) -> BetOutcome:
    """
    Calculate the outcome of a bet given final scores
    
    Args:
        bet: The original bet entry
        final_home_score: Final home team score
        final_away_score: Final away team score
    
    Returns:
        BetOutcome with profit/loss calculated
    """
    from datetime import datetime
    
    actual_spread = final_home_score - final_away_score
    actual_total = final_home_score + final_away_score
    
    # Determine outcome based on bet type
    if bet['bet_type'] == BetType.SPREAD:
        if bet['market_spread'] is None:
            outcome = BetOutcomeStatus.PUSH
        else:
            covered_spread = actual_spread + bet['market_spread']
            
            if bet['bet_side'] == 'home':
                if covered_spread > 0:
                    outcome = BetOutcomeStatus.WON
                elif covered_spread == 0:
                    outcome = BetOutcomeStatus.PUSH
                else:
                    outcome = BetOutcomeStatus.LOST
            else:  # away
                if covered_spread < 0:
                    outcome = BetOutcomeStatus.WON
                elif covered_spread == 0:
                    outcome = BetOutcomeStatus.PUSH
                else:
                    outcome = BetOutcomeStatus.LOST
    else:
        outcome = BetOutcomeStatus.PENDING
    
    # Calculate profit/loss
    if outcome == BetOutcomeStatus.WON:
        # Calculate profit based on American odds
        odds = bet['odds_american']
        if odds < 0:
            profit = bet['bet_amount'] * (100 / abs(odds))
        else:
            profit = bet['bet_amount'] * (odds / 100)
        profit_loss = profit
    elif outcome == BetOutcomeStatus.LOST:
        profit_loss = -bet['bet_amount']
    else:  # PUSH
        profit_loss = 0.0
    
    # ML accuracy
    ml_error = None
    ml_correct = False
    if bet['ml_predicted_spread'] is not None:
        ml_error = abs(bet['ml_predicted_spread'] - actual_spread)
        # ML was "correct" if it predicted the right direction
        ml_correct = (bet['ml_predicted_spread'] > 0 and actual_spread > 0) or \
                     (bet['ml_predicted_spread'] < 0 and actual_spread < 0)
    
    return {
        'bet_id': bet['bet_id'] or 0,
        'game_id': bet['game_id'],
        'final_home_score': final_home_score,
        'final_away_score': final_away_score,
        'actual_spread': actual_spread,
        'actual_total': actual_total,
        'outcome': outcome,
        'profit_loss': profit_loss,
        'roi': (profit_loss / bet['bet_amount'] * 100) if bet['bet_amount'] > 0 else 0,
        'ml_prediction_error': ml_error,
        'ml_was_correct': ml_correct,
        'resolved_at': datetime.now().isoformat()
    }

